[package]
name = "loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
elf = "0.7.2"
log = "0.4.19"
nix = "0.26.2"
simple_logger = "4.2.0"