[package]
name = "coffee"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "coffee"

[dependencies]
anyhow = "1"
elf = "0.7"
log = "0.4"
nix = "0.28"
simple_logger = "4"
libc = "0.2"